// VARIABELS:
// SNAKE: SNAKE CHARATER INCLUDE DIRECTION
// SCORE: CURRENT SCORE
// HIGHESTSCORE: TO SEE THE HIGHEST SCORE
// SNACKOPTIONS:[ARRAY] (APPLE,CANDY,BALL, AND RANDOM) SO PLAYER CAN USE
// DIFFICALTYLEVEL:[ARRAY] (EASY, MEDIUM,AND HARD) LIST THE AVAILABLE LEVEL TO SELECT
// CURRENTDIFFICALTY: TO KNOW THE LEVEL
// TIMER: TO SEE THE TIME AND CALCULATE THE HIGHSTSCORE
// GAMESTARTED: TO KNOW IF THE LEVEL START OR NOT
// GAMEEND: TO KNOW IF THE GAME IS END OR NOT
// FUNCTIONS:
// FUNCTION FOR DISPLAY LADING PAGE WITH GAME PIC , TITLE AND START BUTTON.
// FUNCTION FOR CHOOSING SNACKS OPTIONS DISPLAY SNACK OPTIONS (APPLE,CANDY,BALL, AND RANDOM) [USER SELECT OPTION]
// FUNCTION FOR CHOOSE DIFFICULTY LEVEL DISPLAY DIFFICULTY LEVEL BUTTONS (EASY,MEDIUM,HARD) [USER SELECT THE DIFFICULTY LEVEL]
// FUNCTION TO KNOW IF THE GAME IS STARTED
// FUNCTION FOR CHANGE DIRECTION [KEY] BASED ON KEY INPUT
// FUNCTION TO UPDATE THE SCORE IF ITS THE HIGHEST VALUE OR NOT
// FUNCTION TO START EFFECT OF SOUND
// EVENT LISTENER:
